version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user
    volumes:
      - gestao_pg_data:/bitnami/postgresql

volumes:
  gestao_pg_data:
  # rabbitmq:
  #   image: 'rabbitmq:latest'
  #   environment:
  #     - 'RABBITMQ_DEFAULT_PASS=secret'
  #     - 'RABBITMQ_DEFAULT_USER=myuser'
  #   ports:
  #     - '5672'
